a = range(5)
print(a)
print(list(range(5)))
print(list(range(4,88,7)))
print(abs(-5),abs(3+4j))
print(max(9,12,6,15),max(-2,-7,-35,-4))
print(min(9,12,6,15),min(-2,-7,-35,-4))
print(type(a))
print(type("string"))
print(type(5))
print(type(2+3j))
name=input("May i know your name? ")
print("It's a pleasure to meet you "+name+"!")
age=input("Your age, please? ")
print("So you are "+age+" years old, "+name+"!")
